// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvqrmF6lTMiiE0mC0VtHi2XAKGxmMRVw',
    appId: '1:196671913726:web:395d18e7e017d8bf9eafaf',
    messagingSenderId: '196671913726',
    projectId: 'journalize-653a3',
    authDomain: 'journalize-653a3.firebaseapp.com',
    storageBucket: 'journalize-653a3.appspot.com',
    measurementId: 'G-C8TMDYF1GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejMtfVituaMIXIEHncvbuoWvd7aThv84',
    appId: '1:196671913726:android:86e1282949c49b579eafaf',
    messagingSenderId: '196671913726',
    projectId: 'journalize-653a3',
    storageBucket: 'journalize-653a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKXT2-wxus4ti-exDWEHYWS-iVgWY2yvY',
    appId: '1:196671913726:ios:e04ac065792c046a9eafaf',
    messagingSenderId: '196671913726',
    projectId: 'journalize-653a3',
    storageBucket: 'journalize-653a3.appspot.com',
    iosBundleId: 'com.example.journalize',
  );
}
